# Stubs for docutils.parsers.rst.directives.html (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Dict, List, Match, Tuple, Type, Union

from docutils import nodes
from docutils.parsers.rst import Directive, states

__docformat__: str

class MetaBody(states.SpecializedBody):
    class meta(nodes.Special, nodes.PreBibliographic, nodes.Element): ...
    def field_marker(self, match: Match, context: Any, next_state: str) -> Tuple[List[Any], str, List[Any]]: ...
    def parsemeta(self, match: Match) -> Tuple[Union[nodes.pending, nodes.system_message], bool]: ...

class Meta(Directive):
    has_content: bool = ...
    SMkwargs: Dict[str, Tuple[Type[MetaBody]]] = ...
    def run(self) -> List[nodes.Node]: ...
