name: Lint source code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run:  pip install -U pip flake8 mypy
    - name: Run flake8
      run:  find docutils-stubs -name '*.pyi' -print0 | xargs -0 flake8
    - name: Create symlink for docutils-stubs (for mypy)
      run: test -e docutils || ln -sF docutils-stubs/ docutils
    - name: Run mypy
      run: mypy docutils
